apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo-jaeger
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
    prometheus.io/port: '14269'
    prometheus.io/scrape: 'true'
  name: opentelemetry-demo-jaeger
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: all-in-one
      app.kubernetes.io/instance: opentelemetry-demo
      app.kubernetes.io/name: jaeger
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: '14269'
        prometheus.io/scrape: 'true'
      labels:
        app.kubernetes.io/component: all-in-one
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: jaeger
    spec:
      containers:
        - args:
            - '--memory.max-traces=5000'
            - '--query.base-path=/jaeger/ui'
            - >-
              --prometheus.server-url=http://opentelemetry-demo-prometheus-server:9090
            - '--prometheus.query.normalize-calls=true'
            - '--prometheus.query.normalize-duration=true'
          env:
            - name: METRICS_STORAGE_TYPE
              value: prometheus
            - name: SPAN_STORAGE_TYPE
              value: memory
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ':9411'
            - name: JAEGER_DISABLED
              value: 'false'
            - name: COLLECTOR_OTLP_ENABLED
              value: 'true'
          image: 'registry.cn-hangzhou.aliyuncs.com/private-mesh/hellob:jaeger'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 14269
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          name: jaeger
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 16685
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 14269
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 400Mi
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      serviceAccount: opentelemetry-demo-jaeger
      serviceAccountName: opentelemetry-demo-jaeger
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
  name: opentelemetry-demo-jaeger-collector
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - appProtocol: http
      name: http-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - appProtocol: grpc
      name: grpc-http
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: c-tchan-trft
      port: 14267
      protocol: TCP
      targetPort: 14267
    - appProtocol: http
      name: http-c-binary-trft
      port: 14268
      protocol: TCP
      targetPort: 14268
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - appProtocol: http
      name: web-http
      port: 16686
      protocol: TCP
      targetPort: 16686
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: ClusterIP
