# Options for analysis running.
run:
  # vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-dirs:
    - example
    - test
  skip-files:
    - ".*\\.pb\\.go$"
linters:
  disable-all: true
issues:
  exclude-use-default: true


